<?xml version="1.0" encoding="UTF-8"?>
<project name="AreasGeometricasConstructivas" default="jar" basedir=".">
  <description>Interfaz Swing de geometría constructiva 2D</description>
  <property file="nbproject/private/private.properties"/>
  <property file="nbproject/project.properties"/>
  <target name="init">
    <mkdir dir="${build.classes.dir}"/>
    <mkdir dir="${dist.dir}"/>
  </target>
  <target name="compile" depends="init">
    <javac srcdir="${src.dir}" destdir="${build.classes.dir}" encoding="${source.encoding}"
           source="${javac.source}" target="${javac.target}" includeantruntime="false"/>
  </target>
  <target name="jar" depends="compile">
    <jar destfile="${dist.jar}" basedir="${build.classes.dir}">
      <manifest><attribute name="Main-Class" value="${main.class}"/></manifest>
    </jar>
  </target>
  <target name="run" depends="compile">
    <java classname="${main.class}" fork="true" failonerror="true">
      <classpath><pathelement location="${build.classes.dir}"/></classpath>
    </java>
  </target>
  <target name="run-single" depends="run"/>
  <target name="compile-single" depends="compile"/>
  <target name="clean">
    <delete dir="${build.dir}"/>
    <delete dir="${dist.dir}"/>
  </target>
  <target name="rebuild" depends="clean,jar"/>
</project>
